### PR TITLE
Add support for supplying module via io.Reader (for 1.16 embed.FS support)

### PR DESCRIPTION
**Pull request by eh-steve**

### CODE REVIEW

**Comment by sleepinggenius2** [comment]
This is a start to adding io.Reader support, but there are still limitations with this approach. Now that 1.16 has released, I feel like it is even more important to address io/fs support. Is io.Reader support still needed in the external API in that case? I am not dismissing it, just trying to get a better understanding of the use cases for it that would not be supported by an io/fs-compatible implementation.

**Comment by eh-steve** [comment]
Supporting passing in an `fs.FS` instead of a `io.Reader` would also do what I want (which is to embed MIBs into binaries using embed.FS), but this approach gives users more control of where their MIBs come from (which needn’t necessarily be a filesystem, but could be a network call).

In the case where I’ve used it, I embed all the MIBs in a directory into an `embed.FS`, then in the application code, I list the whole FS directory and loop over the files and then open and load them via the reader interface.

I’d be happy to change to an FS interface if you prefer?

**Comment by sleepinggenius2** [comment]
It would be very rare to have a MIB without imports, which are loaded automatically today, if they can be found in the search path. While all the files can be loaded in the way you describe, your use case sounds like a perfect one for abstracting out the filesystem instead. I would argue that with the way that the fs.FS interface has been designed, there is no reason that the backing implementation couldn't use network calls, object storage, whatever. My thought would be to rewrite all the filesystem-dependent code to use the new io/fs interfaces, while leaving the external API relatively unchanged, except for adding path functions to take one of the FS interfaces instead of a string, then the existing path methods would be updated to use those new methods. I apologize, I have not had the opportunity to properly look into the 1.16 changes yet, so my implementation ideas are very high level at the moment and I welcome feedback.

**Comment by eh-steve** [comment]
Hmmm... that would be quite hard to do while still supporting older versions of Go with this library (as we can't import `io/fs` directly in the library without adding `//+build go1.16` tags in the files which need it, and providing an alternative implementation in other files). If we wanted to store the a user supplied `fs.FS` in the `smiHandle`, we'd need to implement our own FS interface and make a decorator to convert between `fs.FS` and our internal `FS` I think (this function would only be in files with `go1.16` build tags). 

Also to complicate things, the `embed.FS` isn't an `fs.StatFS` so you can't us it as a direct drop-in for the current `os` calls being made.

If we ignore backward compatibility, it'd be quite easy to make the switch though.

What are you thinking?

**Comment by sleepinggenius2** [comment]
Playing around with build tags, I have an implementation written that should continue to support a minimum version of 1.13, while being optimized for 1.16+. I still have some more testing to do, but hopefully will have a release out this week.

**Comment by sleepinggenius2** [comment]
I have now released v0.4.0, including an example using embed.FS. Please let me know if this meets your needs.

**Comment by eh-steve** [comment]
Looks good to me

**Pull request closed without merging**
